### ISSUE TITLE
LI: SLES 15 SP1 system-setup/storage fails if network is not reachable

### ISSUE THREAD

**Issue by prtyag** [SUSE-Enceladus/azure-li-services#164]
SLES 15 SP1 image deployment  is failing due to failure of azure-li-system-setup and azure-li-storage services. As per the instructions mentioned in `/etc/issue` file ran the `systemctl status` command for the failing service.

Following is the result of the `systemctl status -l azure-li-storage azure-li-system-setup`.

 ```
azure-li-storage.service - Setup of Azure Li/VLi Storage Mountpoints

   Loaded: loaded (/usr/lib/systemd/system/azure-li-storage.service; enabled; vendor preset: disabled)

   Active: inactive (dead) since Wed 2019-07-31 11:13:14 UTC; 14min ago

 Main PID: 4275 (code=exited, status=1/FAILURE)

 

Jul 31 11:13:14 azurehost2 azure-li-storage[4275]:     Command.run(['mount', '-a'])

Jul 31 11:13:14 azurehost2 azure-li-storage[4275]:   File "/usr/lib/python3.6/site-packages/azure_li_services/command.py", line 104, in run

Jul 31 11:13:14 azurehost2 azure-li-storage[4275]:     command[0], error.decode(), output.decode()

Jul 31 11:13:14 azurehost2 azure-li-storage[4275]: azure_li_services.exceptions.AzureHostedCommandException: mount: stderr: mount.nfs: Network is unreachable

Jul 31 11:13:14 azurehost2 azure-li-storage[4275]: mount.nfs: Network is unreachable

Jul 31 11:13:14 azurehost2 azure-li-storage[4275]: , stdout: (no output on stdout)

Jul 31 11:13:14 azurehost2 systemd[1]: azure-li-storage.service: Main process exited, code=exited, status=1/FAILURE

Jul 31 11:13:14 azurehost2 systemd[1]: Failed to start Setup of Azure Li/VLi Storage Mountpoints.

Jul 31 11:13:14 azurehost2 systemd[1]: azure-li-storage.service: Unit entered failed state.

Jul 31 11:13:14 azurehost2 systemd[1]: azure-li-storage.service: Failed with result 'exit-code'.

 

● azure-li-system-setup.service - System Setup of Azure Li/VLi machine

   Loaded: loaded (/usr/lib/systemd/system/azure-li-system-setup.service; enabled; vendor preset: disabled)

   Active: inactive (dead) since Wed 2019-07-31 11:13:23 UTC; 14min ago

  Process: 4270 ExecStart=/usr/bin/azure-li-system-setup (code=exited, status=1/FAILURE)

 Main PID: 4270 (code=exited, status=1/FAILURE)

 

Jul 31 11:13:23 azurehost2 azure-li-system-setup[4270]: Traceback (most recent call last):

Jul 31 11:13:23 azurehost2 azure-li-system-setup[4270]:   File "/usr/bin/azure-li-system-setup", line 11, in <module>

Jul 31 11:13:23 azurehost2 azure-li-system-setup[4270]:     load_entry_point('azure-li-services==1.1.31', 'console_scripts', 'azure-li-system-setup')()

Jul 31 11:13:23 azurehost2 azure-li-system-setup[4270]:   File "/usr/lib/python3.6/site-packages/azure_li_services/units/system_setup.py", line 92, in main

Jul 31 11:13:23 azurehost2 azure-li-system-setup[4270]:     raise AzureHostedException(system_setup_errors)

Jul 31 11:13:23 azurehost2 azure-li-system-setup[4270]: azure_li_services.exceptions.AzureHostedException: [AzureHostedCommandException('iscsiadm: stderr: iscsiadm: cannot make connection to 10.250.53.31: Network is unreachable\niscsiadm: cannot make connection to 10.250.53.31: Network is unreachable\niscsiadm: cannot make connection to 10.250.53.31: Network is unreachable\niscsiadm: cannot make connection to 10.250.53.31: Network is unreachable\niscsiadm: cannot make connection to 10.250.53.31: Network is unreachable\niscsiadm: cannot make connection to 10.250.53.31: Network is unreachable\niscsiadm: connection login retries (reopen_max) 5 exceeded\niscsiadm: Could not perform SendTargets discovery: encountered connection failure\n, stdout: (no output on stdout)',)]

Jul 31 11:13:23 azurehost2 systemd[1]: azure-li-system-setup.service: Main process exited, code=exited, status=1/FAILURE

Jul 31 11:13:23 azurehost2 systemd[1]: Failed to start System Setup of Azure Li/VLi machine.

Jul 31 11:13:23 azurehost2 systemd[1]: azure-li-system-setup.service: Unit entered failed state.

Jul 31 11:13:23 azurehost2 systemd[1]: azure-li-system-setup.service: Failed with result 'exit-code'.
```

Note that in this case `systemctl status` command output of azure-li-network service says that 10.250.53.31 is not reachable but the deployment with same configuration YAML works fine when booted with SLES-12-SP3 image.

**Comment by schaefi** [comment]
So both services fails because the network is not reachable. Thus the question should be why is the network not reachable ?

* Is the network setup correct ?
* Is the network reachable after some time ?

**Comment by prtyag** [comment]
I tried following steps to make sure network reachability is not the issue.

1. Tried deploying SLES 15 SP1 but failed due to error(network unreachable)
2. Successfully deployed SLES-12-SP3.
3. Again tried deploying SLES 15 SP1  but failed with a same error.

So I guess there isn't any problem with the network. 

Please let me know if you need  any input regarding this from my side.
