### ISSUE TITLE
Error when specifying group for a user

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#98]
I modified an existing YAML to add the ID/group information, like this:

```
credentials:
 -
  username: "hanauser"
  id: 1005
  group:
    name: hanagroup
    id: 1100
  shadow_hash: "$6$e8JMOsEv4P3rDUJy$NMf11b7JF1e4Lp.J/VnyMdzTdO9O2zHexjkLei5HcRzc/xZWG6JTS0KylGDYprHtlhMFQNzctomit6l7CAKSC1"
```

When I did that, I started getting an error during user setup:

```
● azure-li-user.service - Setup of Azure Li/VLi workload user
   Loaded: loaded (/usr/lib/systemd/system/azure-li-user.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2018-11-30 23:16:43 UTC; 22s ago
 Main PID: 26605 (code=exited, status=1/FAILURE)

Nov 30 23:16:43 linux azure-li-user[26605]: Traceback (most recent call last):
Nov 30 23:16:43 linux azure-li-user[26605]:   File "/usr/bin/azure-li-user", line 9, in <module>
Nov 30 23:16:43 linux azure-li-user[26605]:     load_entry_point('azure-li-services==1.1.14', 'console_scripts', 'azure-li-user')()
Nov 30 23:16:43 linux azure-li-user[26605]:   File "/usr/lib/python3.4/site-packages/azure_li_services/units/user.py", line 74, in main
Nov 30 23:16:43 linux azure-li-user[26605]:     raise AzureHostedException(user_setup_errors)
Nov 30 23:16:43 linux azure-li-user[26605]: azure_li_services.exceptions.AzureHostedException: [TypeError('must be str, not dict',)]
Nov 30 23:16:43 linux systemd[1]: azure-li-user.service: Main process exited, code=exited, status=1/FAILURE
Nov 30 23:16:43 linux systemd[1]: Failed to start Setup of Azure Li/VLi workload user.
Nov 30 23:16:43 linux systemd[1]: azure-li-user.service: Unit entered failed state.
Nov 30 23:16:43 linux systemd[1]: azure-li-user.service: Failed with result 'exit-code'.
```

This was not expected, and I don't understand what the problem is. It looks right when looking at your [test file](https://github.com/SUSE-Enceladus/azure-li-services/blob/master/test/data/config.yaml).

After boot, I find the following in `/etc/passwd`:

```
hanauser:x:1005:1100::/home/hanauser:/bin/bash
```

And in `/etc/group`, I see:

```
hanagroup:x:1100:
admin:x:1101:hanauser
```

Is it expected that group `admin` is created with `hanauser` here, I don't think I asked for that. Perhaps that part is expected; I just wanted to let you know what I saw.

Any idea why I'm seeing this error?

**Comment by schaefi** [comment]
That reads like a bug, but so far I don't know how this could happen. I'll run some tests

**Comment by schaefi** [comment]
Problem found, fix is on its way
